### ISSUE TITLE
Docker Hub repository disappeared

### ISSUE THREAD

**Issue by Talanor** [rcdailey/nextcloud-cronjob#1]
Hello,

https://hub.docker.com/r/voidpointer/nextcloud-cronjob/
Yields a 404.

Regards,

**Comment by awade** [comment]
Still gone it seems.  We can always build from scratch locally.

**Comment by rcdailey** [comment]
Sorry I didn't even see this issue... 

I renamed the account on Docker Hub. The correct URL is:

https://hub.docker.com/r/rcdailey/nextcloud-cronjob/

I have also corrected the link on the main page. Sorry about that!
