### ISSUE TITLE
Custom interval for customized cron jobs

### ISSUE THREAD

**Issue by bondif** [rcdailey/nextcloud-cronjob#16]
Hi,

I'm using a customized cron task to run `php occ files:scan --all`, and since this takes much more time, it doesn't make sense to run it in the same interval as the cron.php file.
Is there a way to have custom intervals for each cron job?

Thank you

**Comment by DMTwo** [comment]
Hi @rcdailey
Firstly, thanks for this awesome project!
I've tried a lot of other ways and the one made by you worked great, I couldn't believe my eyes when it worked in my first attempt.

I believe that this whole topic should be changed to requests and not an actual issue.

In fact, I also would like to have the same functionality to scan all files twice a day (just like @bondif) and rebuild the previews once a day, however in the instruction there's no way to achieve the desired script scheduling.

Could you give us a feedback if this functionality could and would be implemented in the future releases?

**Comment by rcdailey** [comment]
To be honest, I am not going to work on any feature requests here. I simply do not have the time or the interest in it. My personal use case is not that complex.

Sorry I don't have a better answer for you. However I'm always happy to review pull requests.

**Comment by DMTwo** [comment]
Thanks anyway!
