### ISSUE TITLE
Work around for customized cron jobs using custom intervals

### ISSUE THREAD

**Issue by DMTwo** [rcdailey/nextcloud-cronjob#17]
Hi @bondif!

I was searching a way to execute the custom script twice a day (https://github.com/rcdailey/nextcloud-cronjob/issues/16) and tested a successful way to do it.
It probably can be optimized, however it worked for me, and I'm using it in my Nextcloud home installation.

I have set my `NEXTCLOUD_CRON_MINUTE_INTERVAL=5`, in this way I could manage to always have round minutes.
Then I have created the desired script inside the "cron-scripts" folder:
```
#!/bin/sh
DesiredHourMinute=`date +%H:%M` #Hour and minute are getting stored into this variable
if [[ $DesiredHourMinute == "04:00" ]] || [[ $DesiredHourMinute == "16:00" ]]; then
	php occ files:scan --all # Scan all files at the desired hour above
fi
```
> My containers are using UTC, I don't know if there's a way to set them to the local time, but I kept this in mind when I have chosen the time when the scripts should run.

Using this script I achieve the desired full scan twice a day and also it's also registered into the conteiner log:

```
Container Name: nextcloud-app
Found Nextcloud container with ID 26e0a3ffa81e
Chosen shell "bash" was found in the Nextcloud container
Starting crond
-------------------------------------------------------------
 Executing Cron Tasks: Thu Nov 17 22:15:00 UTC 2022
-------------------------------------------------------------
> Nextcloud Container ID: 26e0a3ffa81e
> Running Script: ./run-cron-php.sh
> Running Script: ./Scan-All-Files.sh
Starting scan for user 1 out of 2 (DMTwo)
Starting scan for user 2 out of 2 (User2)
-------------------------------------------------------------
 Executing Cron Tasks: Thu Nov 17 22:20:00 UTC 2022
-------------------------------------------------------------
> Nextcloud Container ID: 26e0a3ffa81e
> Running Script: ./run-cron-php.sh
> Running Script: ./Scan-All-Files.sh
> Done
-------------------------------------------------------------
 Executing Cron Tasks: Thu Nov 17 22:25:00 UTC 2022
-------------------------------------------------------------
> Nextcloud Container ID: 26e0a3ffa81e
> Running Script: ./run-cron-php.sh
> Running Script: ./Scan-All-Files.sh
> Done
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 9998    | 40685 | 00:10:23     |
+---------+-------+--------------+
> Done
```
Hi @rcdailey,
Please if possibly add this work around into your instructions.
I think it can help others using custom scripts.

**I wish the best to you both.
Thanks a lot!**

**Comment by rcdailey** [comment]
I'm happy to accept a PR with the updates you'd like to see.
