### ISSUE TITLE
nvm

### ISSUE THREAD

**Issue by Cookester81** [rcdailey/nextcloud-cronjob#18]
...

**Comment by rcdailey** [comment]
You didn't need to edit your original post before you closed. I think what would be helpful is to restore your original post content and reply with the solution you found. This will help others in the future.

Glad you got past the issue, whatever it was.

**Comment by BadCo-NZ** [comment]
@Cantenna99 can you please fix your issue title and contents and post your solution?

I am currently having a issue with bash not being inside the Nextcloud container, and your information may help me.

```
ERROR: Shell "bash" does not exist in the Nextcloud container
```

I tried changing to sh as per the README, but got the same error as you

```
ERROR: Shell "sh" does not exist in the Nextcloud container
```
