### ISSUE TITLE
Cron is not running

### ISSUE THREAD

**Issue by alekslyse** [rcdailey/nextcloud-cronjob#20]
When starting the docker container it’s starting properly and everything loads properly, even setting up crontab, so entry point.sh is doing everything right, but it doesn’t run cron-tasks.sh if I run it manually it runs the Cron successfully

**Comment by rcdailey** [comment]
Sorry I didn't respond to this sooner. Can you let me know if you're still having an issue?

**Comment by rcdailey** [comment]
Closing due to no response from OP.
