### ISSUE TITLE
crond not starting

### ISSUE THREAD

**Issue by DaGloaDone** [rcdailey/nextcloud-cronjob#23]
Hey :)
First of all thank you for creating this Docker image. I was looking for something like this for ever!
I just have the issue that crond is not starting. see log:

```
Will search for Nexcloud container as a Docker Compose service
Project: nextcloud, Service: app
Found Nextcloud container with ID 623030c27720
Chosen shell "bash" was found in the Nextcloud container
Starting crond
```

after that the log file ends.

How can i fix this?

**Comment by rcdailey** [comment]
There's a way to switch to `sh`. Check the environment variable docs. Does that resolve the issue for you?

**Comment by rcdailey** [comment]
Closing due to lack of response.
