### ISSUE TITLE
Support for Alpine based Nextcloud images

### ISSUE THREAD

**Issue by yareg-com** [rcdailey/nextcloud-cronjob#6]
I tried to setup nextcloud-cronjob with nextcloud:19-fpm-alpine image and got this error:

OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown

I think this is because Alpine OS uses sh instead of bash. It would be great to have this supported.

**Comment by rcdailey** [comment]
Interesting issue. I will look into it.

**Comment by rcdailey** [comment]
Please read the documentation on the newly added environment variables `NEXTCLOUD_EXEC_SHELL` and `NEXTCLOUD_EXEC_SHELL_ARGS`. In your case please use `NEXTCLOUD_EXEC_SHELL=sh`. The args variable already defaults to `-c`. Again, documentation has more detail and examples.

Thank you for reporting this!
